hbiperftest: added a new puptoo template, added few helper functions
redhat-performance/opl pull request #3
Opened 2021-06-08 23:17 UTC by vinaykns

that is useful for the hbiperftests, tally.

2021-06-09 19:49 UTC, jhutar requested changes
This looks very good! Please fix few tiny bits and we are ready to go!

2021-06-09 19:49 UTC, jhutar commented on opl/db.py
> +# get_query_result is a wrapper function that gives query result with providing database
Please move docs string into the function:
```
# this does that
def this_does():
```
=>
```
def this_does():
    """This does that."""
```

2021-06-09 19:49 UTC, jhutar commented on opl/db.py
> +def get_query_result(db_conf, sql):
Hello! Why do we need this function? Usually you do not pass DB hostname, creds..., you just pass DB client object. Feel free to keep it in the PR, just wanted to warn you that this way the script needs to connect to the DB for every query, which takes lots of time when compared to connecting once and just passing client object.

2021-06-09 19:49 UTC, jhutar commented on opl/db.py
> +def load_distinct_accounts(inventory_db_conf, d_dict):
This is very HBI specific. Please move to `opl/inventory.py` or so.

2021-06-09 19:49 UTC, jhutar commented on opl/db.py
> +def get_unique_key(d_dict):
Also, this should not be in generic `opl/db.py`.

2021-06-09 19:49 UTC, jhutar commented on opl/generators/inventory_ingress.py
> +    def _get_service_data(self):
Why do we need this function? Can we create `enabed_services`, `yum_repos`... directly in `_get()` function? E.g.:

```
        data = {
                  'subscription_manager_id': self._get_uuid(),
                  'bios_uuid': self._get_bios_uuid(),
                  'request_id': self._get_uuid(),
                  'owner_id': self._get_uuid(),
                  'insights_id': self._get_uuid(),
                  'ipv4_addr': self._get_ipv4(),
                  'ipv6_addr': self._get_ipv6(),
                  'mac_addr': self._get_mac(),
                  'fqdn': self._get_hostname(),
                  'nowz': self._get_now_iso_z(),   # well, this is in nano-seconds, but should be in mili-seconds
                  'tommorowz': self._get_tommorow_iso_z(),
                  'packages': self.pg.generate(self.packages),
                  'yum_repos': opl.generators.packages.YumReposGenerator().generate(137),
                  'enabled_services': opl.generators.packages.EnabledServicesGenerator().generate(139),
                  'installed_services': opl.generators.packages.InstalledServicesGenerator() .generate(160),
                  'running_processes': opl.generators.packages.RunningProcessesGenerator().generate(89),
        }
```
Or you can create helper functions like:
```
def _get_yum_repos(self):
    return opl.generators.packages.YumReposGenerator().generate(137)
```
and then just have:
```
        data = {
                  'subscription_manager_id': self._get_uuid(),
                  'bios_uuid': self._get_bios_uuid(),
                  'request_id': self._get_uuid(),
                  'owner_id': self._get_uuid(),
                  'insights_id': self._get_uuid(),
                  'ipv4_addr': self._get_ipv4(),
                  'ipv6_addr': self._get_ipv6(),
                  'mac_addr': self._get_mac(),
                  'fqdn': self._get_hostname(),
                  'nowz': self._get_now_iso_z(),   # well, this is in nano-seconds, but should be in mili-seconds
                  'tommorowz': self._get_tommorow_iso_z(),
                  'packages': self.pg.generate(self.packages),
                  'yum_repos': self._get_yum_repos(),
                  ...
        }
```

2021-06-09 19:49 UTC, jhutar commented on opl/generators/packages.py
> +class YumReposGenerator:
Nice!

2021-06-09 23:05 UTC, vinaykns commented
@jhutar  please take another look.

2021-06-10 07:23 UTC, jhutar commented on opl/generators/inventory_ingress.py
> +        data.update({'b64_identity': self._get_b64_identity(data['account'])})
You can put this `'b64_identity': self._get_b64_identity(data['account'])` directly above where we create `data` variable, but this works as well.

2021-06-10 07:24 UTC, merged

2021-06-10 07:24 UTC, jhutar commented
Thank you!